config/routes.rb
Rails.application.routes.draw do

  get 'control_users/index'

  devise_for :users
  root 'welcome#index'
  resources :sangues
  resources :doadors

  resources :faq

  get 'welcome' => 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doador.rb
class Doador < ApplicationRecord
end

app/models/sangue.rb
class Sangue < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  enum role: [:normal_user, :admin]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

include Pundit

before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized



private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:idade])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:telefone])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:endereco])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:cpf])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:tipo_sanguineo])
  end

  def user_not_authorized
    flash[:notice] = "Você não tem permissão para fazer esta ação"
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @users = User.all
    authorize @users
  end
end

app/controllers/doadors_controller.rb
class DoadorsController < ApplicationController
  before_action :set_doador, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /doadors
  # GET /doadors.json
  def index
    @doadors = Doador.all
  end

  # GET /doadors/1
  # GET /doadors/1.json
  def show
  end

  # GET /doadors/new
  def new
    @doador = Doador.new
  end

  # GET /doadors/1/edit
  def edit
  end

  # POST /doadors
  # POST /doadors.json
  def create
    @doador = Doador.new(doador_params)

    respond_to do |format|
      if @doador.save
        format.html { redirect_to @doador, notice: 'Doador was successfully created.' }
        format.json { render :show, status: :created, location: @doador }
      else
        format.html { render :new }
        format.json { render json: @doador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doadors/1
  # PATCH/PUT /doadors/1.json
  def update
    respond_to do |format|
      if @doador.update(doador_params)
        format.html { redirect_to @doador, notice: 'Doador was successfully updated.' }
        format.json { render :show, status: :ok, location: @doador }
      else
        format.html { render :edit }
        format.json { render json: @doador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doadors/1
  # DELETE /doadors/1.json
  def destroy
    @doador.destroy
    respond_to do |format|
      format.html { redirect_to doadors_url, notice: 'Doador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doador
      @doador = Doador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doador_params
      params.require(:doador).permit(:nome, :idade, :telefone, :email, :cpf, :endereco, :tipo_sanguineo)
    end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
	def index
	end
end

app/controllers/sangues_controller.rb
class SanguesController < ApplicationController
  before_action :set_sangue, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /sangues
  # GET /sangues.json
  def index
    @sangues = Sangue.all
  end

  # GET /sangues/1
  # GET /sangues/1.json
  def show
  end

  # GET /sangues/new
  def new
    @sangue = Sangue.new
  end

  # GET /sangues/1/edit
  def edit
  end

  # POST /sangues
  # POST /sangues.json
  def create
    @sangue = Sangue.new(sangue_params)

    respond_to do |format|
      if @sangue.save
        format.html { redirect_to @sangue, notice: 'Sangue was successfully created.' }
        format.json { render :show, status: :created, location: @sangue }
      else
        format.html { render :new }
        format.json { render json: @sangue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sangues/1
  # PATCH/PUT /sangues/1.json
  def update
    respond_to do |format|
      if @sangue.update(sangue_params)
        format.html { redirect_to @sangue, notice: 'Sangue was successfully updated.' }
        format.json { render :show, status: :ok, location: @sangue }
      else
        format.html { render :edit }
        format.json { render json: @sangue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sangues/1
  # DELETE /sangues/1.json
  def destroy
    @sangue.destroy
    respond_to do |format|
      format.html { redirect_to sangues_url, notice: 'Sangue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sangue
      @sangue = Sangue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sangue_params
      params.require(:sangue).permit(:tipo, :quantidade)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_users_helper.rb
module ControlUsersHelper
end

app/helpers/doadors_helper.rb
module DoadorsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/sangues_helper.rb
module SanguesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/control_users/index.html.erb
<h1>Lista de Usuários</h1>
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sobrenome</th>
      <th>Idade</th>
      <th>Email</th>
      <th>Role</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.idade %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/doadors/_form.html.erb
<%= form_with(model: doador, local: true) do |form| %>
  <% if doador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doador.errors.count, "error") %> prohibited this doador from being saved:</h2>

      <ul>
      <% doador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :doador_nome %>
  </div>

  <div class="field">
    <%= form.label :idade %>
    <%= form.number_field :idade, id: :doador_idade %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :doador_telefone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :doador_email %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, id: :doador_cpf %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco, id: :doador_endereco %>
  </div>

  <div class="field">
    <%= form.label :tipo_sanguineo %>
    <%= form.text_field :tipo_sanguineo, id: :doador_tipo_sanguineo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doadors/_form_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @doador.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @doador.idade %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @doador.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @doador.email %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @doador.cpf %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @doador.endereco %>
</p>

<p>
  <strong>Tipo sanguineo:</strong>
  <%= @doador.tipo_sanguineo %>
</p>

<%= link_to 'Edit', edit_doador_path(@doador) %> |
<%= link_to 'Back', doadors_path %>

app/views/doadors/edit.html.erb
<h1>Editing Doador</h1>

<%= render 'form', doador: @doador %>

<%= link_to 'Show', @doador %> |
<%= link_to 'Back', doadors_path %>

app/views/doadors/index.html.erb
<% if current_user.admin? %>
<%= link_to 'New Doador', new_doador_path %>

<!DOCTYPE html>
<html>
<head>
  <title>Doadores</title>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheets" href="assets/stylesheets/bootstrap.css">
</head>
<body>
 <p id="notice"><%= notice %></p>

<h1>Doadores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>Cpf</th>
      <th>Endereco</th>
      <th>Tipo sanguineo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doadors.each do |doador| %>
      <tr>
        <td><%= doador.nome %></td>
        <td><%= doador.idade %></td>
        <td><%= doador.telefone %></td>
        <td><%= doador.email %></td>
        <td><%= doador.cpf %></td>
        <td><%= doador.endereco %></td>
        <td><%= doador.tipo_sanguineo %></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Show', doador %></td>
        <td><%= link_to 'Edit', edit_doador_path(doador) %></td>
        <td><%= link_to 'Destroy', doador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</body>
</html>



<%else%>

<!DOCTYPE html>
<html>
<head>
  <title>Meu cadastro</title>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheets" href="assets/stylesheets/bootstrap.css">
</head>
<body>
 <p id="notice"><%= notice %></p>

<h1>Meu cadastro</h1>


<table class="table">
  <tbody>
    <tr>
      <td>Nome :</td>
      <td><%=  %></td>
    </tr>
    <tr>
      <td>Idade :</td>
      <td>Thornton</td>
    </tr>
    <tr>
      <td>Telefone :</td>
      <td>the Bird</td>
    </tr>
    <tr>
      <td>Email :</td>
      <td>the Bird</td>
    </tr>
    <tr>
      <td>Cpf :</td>
      <td>the Bird</td>
    </tr>
    <tr>
      <td>Endereço :</td>
      <td>the Bird</td>
    </tr>
    <tr>
      <td>Tipo sanguíneo :</td>
      <td>the Bird</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>Cpf</th>
      <th>Endereco</th>
      <th>Tipo sanguineo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doadors.each do |doador| %>
      <tr>
        <td><%= doador.nome %></td>
        <td><%= doador.idade %></td>
        <td><%= doador.telefone %></td>
        <td><%= doador.email %></td>
        <td><%= doador.cpf %></td>
        <td><%= doador.endereco %></td>
        <td><%= doador.tipo_sanguineo %></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Show', doador %></td>
        <td><%= link_to 'Edit', edit_doador_path(doador) %></td>
        <td><%= link_to 'Destroy', doador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</body>
</html>




<% end %>

app/views/doadors/new.html.erb
<h1>New Doador</h1>

<%= render 'form', doador: @doador %>

<%= link_to 'Back', doadors_path %>

app/views/doadors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @doador.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @doador.idade %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @doador.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @doador.email %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @doador.cpf %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @doador.endereco %>
</p>

<p>
  <strong>Tipo sanguineo:</strong>
  <%= @doador.tipo_sanguineo %>
</p>

<%= link_to 'Edit', edit_doador_path(@doador) %> |
<%= link_to 'Back', doadors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheets" href="assets/stylesheets/bootstrap.css">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


<% if user_signed_in? %> 

<nav class="navbar fixed-top navbar-light bg-light">
  <a class="navbar-brand" href="/welcome"><i class="fa fa-home" aria-hidden="true"></i></a>
  <dev class="navbar-brand"><strong><em><%= link_to "Meu cadastro", doadors_path %></em></strong></dev>
  <div class="navbar-brand" ><strong><em><%= link_to "Sair" , destroy_user_session_path, method: :delete %></em></strong></div>
  <a class="navbar-brand" href="/faq"><strong><em>FAQ</em></strong></a>
  
</nav>

<%else%>

<nav class="navbar fixed-top navbar-light bg-light">
  <a class="navbar-brand" href="/welcome"><i class="fa fa-home" aria-hidden="true"></i></a>
  <a class="navbar-brand" href="/users/sign_up"><strong><em>Cadastro</em></strong></a>
  <a class="navbar-brand" href="/users/sign_in"><strong><em>Login</em></strong></a>
  <a class="navbar-brand" href="/faq"><strong><em>FAQ</em></strong></a>
  
</nav>
<%end%>

    <%= yield %>
  </body>
</html>

app/views/sangues/_form.html.erb
<%= form_with(model: sangue, local: true) do |form| %>
  <% if sangue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sangue.errors.count, "error") %> prohibited this sangue from being saved:</h2>

      <ul>
      <% sangue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo, id: :sangue_tipo %>
  </div>

  <div class="field">
    <%= form.label :quantidade %>
    <%= form.text_field :quantidade, id: :sangue_quantidade %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sangues/edit.html.erb
<h1>Editing Sangue</h1>

<%= render 'form', sangue: @sangue %>

<%= link_to 'Show', @sangue %> |
<%= link_to 'Back', sangues_path %>

app/views/sangues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sangues</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Quantidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sangues.each do |sangue| %>
      <tr>
        <td><%= sangue.tipo %></td>
        <td><%= sangue.quantidade %></td>
        <td><%= link_to 'Show', sangue %></td>
        <td><%= link_to 'Edit', edit_sangue_path(sangue) %></td>
        <td><%= link_to 'Destroy', sangue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sangue', new_sangue_path %>

app/views/sangues/new.html.erb
<h1>New Sangue</h1>

<%= render 'form', sangue: @sangue %>

<%= link_to 'Back', sangues_path %>

app/views/sangues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @sangue.tipo %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @sangue.quantidade %>
</p>

<%= link_to 'Edit', edit_sangue_path(@sangue) %> |
<%= link_to 'Back', sangues_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheets" href="assets/stylesheets/bootstrap.css">
    <title>Home</title>
</head>
<body>
 <p id="notice"><%= notice%></p>

  <h1><img id = "h1" src = "Primeiro.jpg" alt = "Hemocentro" ></h1>

  <h2><strong><em>Porque doar sangue?</em></strong></h2>


  <figure id = "logo">
    <img  src = "logo_hemocentro.png">
    <figcaption>fundaçao hemocentro de brasilia</figcaption>
  </figure>



  <p id = "text">O sangue é um tecido conjuntivo produzido pela medula óssea que
    realiza várias funções no organismo. É composto por plasma, glóbulos brancos, glóbulos vermelhos, hemácias, plaquetas, sais, vitaminas, água e fatores de coagulação.

    A doação de sangue consiste em um ato voluntário de permitir a retirada do seu próprio sangue para beneficiar as pessoas que necessitam receber sangue por qualquer motivo. Infelizmente ainda não foi encontrado nenhum substituto para o sangue, ou seja, é um tecido de extrema importância e valor, pois a sua ausência resulta em morte.

    Para doar sangue o indivíduo preenche um cadastro com seus dados pessoais para que seja cadastrado como doador e ainda para que seja produzida sua carteira de doador. Após o cadastro o mesmo é levado até um profissional que irá verificar seu peso, batimentos cardíacos e pressão arterial. Depois é submetido a exames e à triagem clínica, onde responde perguntas importantes sobre sua condição física.

    Depois de realizados todos os procedimentos necessários, o indivíduo que estiver apto a doar sangue é encaminhado à sala de coleta, onde são retirados 450 ml de sangue do seu braço. Após a doação um lanche é servido ao doador que precisará tomar muito líquido no decorrer do dia.

    A bolsa que recebe o sangue retirado é encaminhada ao fracionamento, onde será separada em até quatro componentes (hemácias, plasmas, plaquetas e fatores de coagulação) que em seguida são levados ao local onde serão armazenados até que sua utilização seja necessária.

    O indivíduo ao doar sangue não apresenta nenhuma manifestação corpórea. Os cuidados após a coleta são: evitar dobrar o braço pelo qual o sangue foi retirado, evitar esforço físico no dia da coleta, manter o curativo por até quatro horas, não fumar nas primeiras duas horas e não ingerir bebidas alcoólicas nas próximas doze horas.
  </p>


  <h2>Tipos sanguíneos</h2>

  <ul class="list-group">
      <li class="list-group-item"><strong><em>A+</em></strong></li>
      <li class="list-group-item"><strong><em>A-</em></strong></li>
      <li class="list-group-item"><strong><em>B+</em></strong></li>
      <li class="list-group-item"><strong><em>B-</em></strong></li>
      <li class="list-group-item"><strong><em>AB+</em></strong></li>
      <li class="list-group-item"><strong><em>AB-</em></strong></li>
      <li class="list-group-item"><strong><em>O+</em></strong></li>
      <li class="list-group-item"><strong><em>O-</em></strong></li>
   </ul>

   <h2>Relações</h2>


   <figure id = "relacoes"">

    <img src="relacoes.png" alt="Relações">
    <figcaption>Relaçoes</figcaption>

   </figure>




 <!--  </div>
 <% if user_signed_in? %>
     <ul>
       <li><%= current_user.email %></li>
       <li><%= link_to "Sair" , destroy_user_session_path, method: :delete %></li>
     </ul>
   <% if current_user.admin? %>
     <ul>
       <li><%= link_to "Doadores", doadors_path %></li>
       <li><%= link_to "Banco de Sangue", sangues_path %></li>
       <li><%= link_to "Usuários", control_users_index_path %></li>
     </ul>
   <% else %>
     <ul>
       <li><%= link_to "Meu cadastro", doadors_path %></li>
     </ul>
   <% end %>

 <% else %>
   <ul>
    <li><%= link_to "Cadastrar" , new_user_registration_path %></li>
     <li><%= link_to "Logar" , new_user_session_path %></li>
   </ul>
 <% end %> 

 <li><%= link_to "Usuários", control_users_index_path %></li>-->

</body>
</html>